# Generated by Django 5.0.7 on 2024-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_ticket_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='remaining_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
